version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    allow:
      - dependency-name: "com.gradle*"
    schedule:
      interval: "daily"
      time: "16:25"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
